name: CI-CD
on:
 push:
    branches:["main"]
workflow_dispatch:
jobs:
 CI:
 runs-on: ubuntu-latest
 steps:
  - name: Obtendo o codigo
    uses: actions/checkout@v4.2.2
  - run: echo "Docker Login" 
    name: Login to Docker Hub
    uses: docker/login-action@v3
    with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  name: Construção 
  uses: docker/build/push
CD: 
runs-on: ubuntu-latest
 steps:
   - run: echo "obter codigo"
   - run: echo "Configurar o Kubernetes"
   - run: echo "Executar o "
  
